CREATE TABLE IF NOT EXISTS customers
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(254) UNIQUE NOT NULL,
    enabled    BOOLEAN DEFAULT TRUE NOT NULL,
    password   VARCHAR(255) NOT NULL,
    first_name VARCHAR(80),
    last_name  VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS authorities
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email     VARCHAR(254) NOT NULL,
    authority VARCHAR(80) NOT NULL,
    CONSTRAINT fk_authority_customer
        FOREIGN KEY (email) REFERENCES customers (email) ON DELETE CASCADE,
    CONSTRAINT uq_authority UNIQUE (email, authority)
);

CREATE TABLE IF NOT EXISTS carts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT UNIQUE NOT NULL,
    total_price NUMERIC(12, 2) DEFAULT 0 NOT NULL,
    CONSTRAINT ck_cart_total_nonnegative CHECK (total_price >= 0),
    CONSTRAINT fk_cart_customer
        FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS restaurants
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(160) UNIQUE NOT NULL,
    address   VARCHAR(300),
    image_url VARCHAR(1000),
    phone     VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS menu_items
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL,
    name          VARCHAR(200) NOT NULL,
    price         NUMERIC(12, 2) NOT NULL,
    description   VARCHAR(2000),
    image_url     VARCHAR(1000),
    CONSTRAINT ck_menu_price_nonnegative CHECK (price >= 0),
    CONSTRAINT fk_menu_restaurant
        FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE,
    CONSTRAINT uq_menu_item UNIQUE (restaurant_id, name)
);

CREATE TABLE IF NOT EXISTS order_items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_item_id BIGINT NOT NULL,
    cart_id      BIGINT NOT NULL,
    price        NUMERIC(12, 2) NOT NULL,
    quantity     INTEGER NOT NULL,
    CONSTRAINT ck_order_price_nonnegative CHECK (price >= 0),
    CONSTRAINT ck_order_quantity_positive CHECK (quantity > 0),
    CONSTRAINT fk_order_cart
        FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE CASCADE,
    CONSTRAINT fk_order_menu_item
        FOREIGN KEY (menu_item_id) REFERENCES menu_items (id) ON DELETE RESTRICT,
    CONSTRAINT uq_cart_menu_item UNIQUE (cart_id, menu_item_id)
);

CREATE INDEX IF NOT EXISTS idx_menu_items_restaurant ON menu_items (restaurant_id);
CREATE INDEX IF NOT EXISTS idx_order_items_cart ON order_items (cart_id);
CREATE INDEX IF NOT EXISTS idx_authorities_email ON authorities (email);
